// server/dataBase/session.js
// Mock sessions data moved out from sessionController
sessions = [
  {
    id: 1,
    studentId: '2311327',
    subject: 'Giải Tích 1',
    tutor: 'Nguyễn Văn A',
    tutorId: 'GV101',     
    time: '14:00 - 16:00',
    date: '2025-11-25',
    status: 'Sắp diễn ra',
    room: 'B4-101',
    description: 'Giới hạn và tính liên tục của hàm',
    materials: [
      { name: 'Slide bài giảng', url: '/files/giai-tich-1-slide.pdf' },
      { name: 'Bài tập về nhà', url: '/files/giai-tich-1-baitap.pdf' }
    ],
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 2,
    studentId: '2311327',
    subject: 'Kỹ thuật lập trình',
    tutor: 'Trần Thị B',
    tutorId: 'GV102',            
    time: '09:00 - 11:00',
    date: '2025-11-24',
    status: 'Đã diễn ra',
    room: 'B4-102',
    description: 'Pointer và Dynamic Memory',
    materials: [
      { name: 'Slide bài giảng', url: '/files/ky-thuat-lap-trinh-slide.pdf' }
    ],
    attendanceRequested: true,
    isAttended: true
  },
  {
    id: 3,
    studentId: '2311327',
    subject: 'Cấu trúc dữ liệu và Giải thuật',
    tutor: 'Lê Minh C',
    tutorId: 'GV103',             
    time: '16:00 - 18:00',
    date: '2025-11-26',
    status: 'Sắp diễn ra',
    room: 'B4-103',
    description: 'Cây nhị phân và duyệt cây',
    materials: [
      { name: 'Slide bài giảng', url: '/files/cau-truc-du-lieu-slide.pdf' },
      { name: 'Code ví dụ', url: '/files/cau-truc-du-lieu-code.zip' }
    ],
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 5,
    studentId: '2311327',
    subject: 'Giải Tích 2',
    tutor: 'Phạm Thị E',
    tutorId: 'GV104',          
    time: '10:00 - 12:00',
    date: '2025-11-27',
    status: 'Sắp diễn ra',
    room: 'B4-104',
    description: 'Hàm nhiều biến và đạo hàm riêng',
    materials: [
      { name: 'Slide bài giảng', url: '/files/giai-tich-2-slide.pdf' }
    ],
    attendanceRequested: true,
    isAttended: false
  },
  {
    id: 6,
    studentId: '2311327',
    subject: 'Đại số tuyến tính',
    tutor: 'Trần Văn F',
    tutorId: 'GV105',            
    time: '13:00 - 15:00',
    date: '2025-11-23',
    status: 'Đã diễn ra',
    room: 'B4-105',
    description: 'Ma trận và định thức',
    materials: [
      { name: 'Slide bài giảng', url: '/files/dai-so-tuyen-tinh-slide.pdf' },
      { name: 'Bài tập về nhà', url: '/files/dai-so-tuyen-tinh-baitap.pdf' }
    ],
    attendanceRequested: true,
    isAttended: true
  },

  {
    id: 11,
    studentId: 'SV002',
    subject: 'Lập trình hướng đối tượng',
    tutor: 'Trần Thị E',
    tutorId: 'GV106',           
    time: '09:00 - 11:00',
    date: '2025-11-20',
    status: 'Đã diễn ra',
    room: 'B1-301',
    description: 'Kế thừa và Đa hình',
    materials: [
      { name: 'OOP_Inheritance.pdf', url: '/files/oop1.pdf' },
      { name: 'Polymorphism_Examples.pptx', url: '/files/oop2.pptx' }
    ],
    feedback: null,
    attendanceRequested: true,
    isAttended: true
  },
  {
    id: 12,
    studentId: 'SV002',
    subject: 'Cơ sở dữ liệu',
    tutor: 'Nguyễn Văn F',
    tutorId: 'GV107',            
    time: '13:00 - 15:00',
    date: '2025-11-22',
    status: 'Đã diễn ra',
    room: 'B2-204',
    description: 'SQL và Relational Database',
    materials: [
      { name: 'SQL_Basics.pdf', url: '/files/sql1.pdf' }
    ],
    feedback: null,
    attendanceRequested: true,
    isAttended: true
  },
  {
    id: 13,
    studentId: 'SV002',
    subject: 'Hệ điều hành',
    tutor: 'Lê Văn G',
    tutorId: 'GV108',              
    time: '15:00 - 17:00',
    date: '2025-11-27',
    status: 'Sắp diễn ra',
    room: 'B3-105',
    description: 'Process và Thread Management',
    materials: [],
    feedback: null,
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 14,
    studentId: 'SV002',
    subject: 'Mạng máy tính',
    tutor: 'Phạm Thị H',
    tutorId: 'GV109',           
    time: '10:00 - 12:00',
    date: '2025-11-28',
    status: 'Sắp diễn ra',
    room: 'B4-201',
    description: 'TCP/IP Protocol',
    materials: [],
    feedback: null,
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 15,
    studentId: 'SV002',
    subject: 'Trí tuệ nhân tạo',
    tutor: 'Đỗ Văn I',
    tutorId: 'GV110',
    time: '08:00 - 10:00',
    date: '2025-12-01',
    status: 'Sắp diễn ra',
    room: 'B1-402',
    description: 'Machine Learning cơ bản',
    materials: [],
    feedback: null,
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 16,
    studentId: 'SV002',
    subject: 'Công nghệ phần mềm',
    tutor: 'Hoàng Văn K',
    tutorId: 'GV111',
    time: '14:00 - 16:00',
    date: '2025-12-03',
    status: 'Sắp diễn ra',
    room: 'B2-303',
    description: 'Agile và Scrum',
    materials: [],
    feedback: null,
    attendanceRequested: false,
    isAttended: false
  },
  {
    id: 17,
    studentId: 'SV002',
    subject: 'Lập trình hướng đối tượng',
    tutor: 'Trần Thị E',
    tutorId: 'GV106',
    time: '16:00 - 18:00',
    date: '2025-12-05',
    status: 'Sắp diễn ra',
    room: 'B1-301',
    description: 'Design Patterns',
    materials: [],
    feedback: null,
    attendanceRequested: false,
    isAttended: false
  }
];


// Dữ liệu lớp học của tutor (classes/sections)
const classes = [
  // Copy NGUYÊN nội dung mảng this.classes trong constructor
    {
        id: 1,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Kiến trúc Máy tính',
        classCode: 'CO2007',
        subject: 'Kiến trúc Máy tính',
        date: '2025-10-05',
        time: '16:55',
        description: 'Bộ nhớ và Cache',
        format: 'On site',
        location: 'B1-303',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 30
    },
    {
        id: 2,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Cấu trúc rời rạc',
        classCode: 'CO1007',
        subject: 'Cấu trúc rời rạc',
        date: '2025-10-06',
        time: '16:05',
        description: 'Ứng dụng toán rời rạc',
        format: 'Không có',
        location: 'B1-303',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 28
    },
    {
        id: 3,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Kỹ thuật lập trình',
        classCode: 'CO1027',
        subject: 'Kỹ thuật lập trình',
        date: '2025-11-24',
        time: '16:55',
        description: 'OOP nâng cao',
        format: 'Off site',
        location: 'H6-506',
        onlineLink: 'Google Meet',
        status: 'Sắp diễn ra',
        studentCount: 35
    },
    {
        id: 4,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Cấu trúc dữ liệu',
        classCode: 'CO2003',
        subject: 'Cấu trúc dữ liệu',
        date: '2025-12-10',
        time: '17:45',
        description: 'Cấu trúc cây nâng cao',
        format: 'Both',
        location: 'B2-404',
        onlineLink: 'Google Meet',
        status: 'Sắp diễn ra',
        studentCount: 32
    },
    {
        id: 5,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Cơ sở dữ liệu',
        classCode: 'CO3025',
        subject: 'Cơ sở dữ liệu',
        date: '2025-12-15',
        time: '14:00',
        description: 'Database Design',
        format: 'On site',
        location: 'B3-201',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 25
    },
    {
        id: 6,
        tutorId: 'GV001',
        tutor: 'Đoàn Minh V',
        className: 'Lập trình hệ thống',
        classCode: 'CO3041',
        subject: 'Lập trình hệ thống',
        date: '2025-12-20',
        time: '15:00',
        description: 'System Call và API',
        format: 'Off site',
        location: 'B4-105',
        onlineLink: 'Microsoft Teams',
        status: 'Sắp diễn ra',
        studentCount: 20
    },
    {
        id: 7,
        tutorId: 'GV002',
        tutor: 'Trần Văn A',
        className: 'Giải Tích 1',
        classCode: 'MA1001',
        subject: 'Giải Tích 1',
        date: '2025-11-10',
        time: '08:00',
        description: 'Giới hạn và đạo hàm',
        format: 'On site',
        location: 'B4-201',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 45
    },
    {
        id: 8,
        tutorId: 'GV002',
        tutor: 'Trần Văn A',
        className: 'Đại số tuyến tính',
        classCode: 'MA2001',
        subject: 'Đại số tuyến tính',
        date: '2025-11-17',
        time: '10:00',
        description: 'Ma trận và định thức',
        format: 'Both',
        location: 'B4-105',
        onlineLink: 'Google Meet',
        status: 'Sắp diễn ra',
        studentCount: 40
    },
    {
        id: 9,
        tutorId: 'GV003',
        tutor: 'Trương Thiên Â',
        className: 'Cấu trúc dữ liệu và Giải thuật',
        classCode: 'CO2003',
        subject: 'Cấu trúc dữ liệu và Giải thuật',
        date: '2025-11-25',
        time: '13:30',
        description: 'Cây nhị phân và duyệt cây',
        format: 'On site',
        location: 'H6-305',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 38
    },
    {
        id: 10,
        tutorId: 'GV003',
        tutor: 'Trương Thiên Â',
        className: 'Cơ sở dữ liệu',
        classCode: 'CO3025',
        subject: 'Cơ sở dữ liệu',
        date: '2025-12-02',
        time: '15:00',
        description: 'Chuẩn hoá và thiết kế lược đồ',
        format: 'Off site',
        location: 'Online',
        onlineLink: 'Zoom',
        status: 'Sắp diễn ra',
        studentCount: 42
    },
    {
        id: 11,
        tutorId: 'GV004',
        tutor: 'Lại Nguyễn Hoàng H',
        className: 'Lập trình Web',
        classCode: 'CO3050',
        subject: 'Lập trình Web',
        date: '2025-12-08',
        time: '09:30',
        description: 'Frontend với React cơ bản',
        format: 'Both',
        location: 'B3-202',
        onlineLink: 'Google Meet',
        status: 'Sắp diễn ra',
        studentCount: 36
    },
    {
        id: 12,
        tutorId: 'GV004',
        tutor: 'Lại Nguyễn Hoàng H',
        className: 'Trí tuệ nhân tạo',
        classCode: 'CO4012',
        subject: 'Trí tuệ nhân tạo',
        date: '2025-12-15',
        time: '13:30',
        description: 'Tổng quan AI và thuật toán tìm kiếm',
        format: 'On site',
        location: 'B2-401',
        onlineLink: null,
        status: 'Sắp diễn ra',
        studentCount: 30
    }

];

module.exports = {
  sessions,
  classes
};
